SoftwareProjects/urls.py
from django.conf.urls.defaults import patterns, url
from SoftwareStories.SoftwareProjects.views import project_create, project_read, projects_read, project_update, project_delete, editor_create, viewer_create, project_canvas, tab_create, tabitem_update, tabitem_create, sitemap_read, tab_update, stories_read, viewer_delete

urlpatterns = patterns('',
                       url(r'^create/$', project_create, name='project_create'),
                       url(r'^list/$', projects_read, name='projects_read'),
                       url(r'^(\d+)/$', project_read, name='project_read'),
                       url(r'^(\d+)/map/$', sitemap_read, name='sitemap_read'),
                       url(r'^(\d+)/update/$', project_update, name='project_update'),
                       url(r'^(\d+)/delete/$', project_delete, name='project_delete'),
                       url(r'^(\d+)/viewer/create/$', viewer_create, name='viewer_create'),
                       url(r'^(\d+)/viewer/(\d+)/delete/$', viewer_delete, name='viewer_delete'),
                       url(r'^(\d+)/editor/create/$', editor_create, name='editor_create'),
                       url(r'^(\d+)/canvas/$', project_canvas, name='project_canvas'),
                       url(r'^(\d+)/tab/create/$', tab_create, name='tab_create'),
                       url(r'^(\d+)/tab/update/(\d+)/$', tab_update, name='tab_update'),
                       url(r'^(\d+)/tabitem/create/$', tabitem_create, name='tabitem_create'),
                       url(r'^(\d+)/tabitem/(\d+)/update/$', tabitem_update, name='tabitem_update'),
                       url(r'^(\d+)/stories/$', stories_read, name='stories_read'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from SoftwareStories.WebDrawing.models import *
from SoftwareStories.UserCenter.models import *
from SoftwareStories.SoftwareProjects.models import *

admin.site.register(TabItem)
admin.site.register(Category)
admin.site.register(PageItem)
admin.site.register(SoftwareStory)
admin.site.register(Project)
admin.site.register(ProjectEditors)
admin.site.register(ProjectViewers)
admin.site.register(Tabs)
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^project/', include('SoftwareProjects.urls')),
                       url(r'^accounts/', include('UserCenter.urls')),
                       url(r'^admin/', include(admin.site.urls)),
)

SoftwareProjects/models.py
from django.db import models
from SoftwareStories.WebDrawing.models import PageItem
from django.contrib.auth.models import User

class Project(models.Model):
    user = models.ForeignKey(User,editable=False)
    title = models.CharField(max_length=200,unique=True)
    description = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["title"]
    def __str__(self):
        return self.title
    
class Tabs(models.Model):
    parentProject = models.ForeignKey(Project,editable=False)
    parentTab = models.ForeignKey('self',blank=True,null=True,default=None)
    title = models.CharField(max_length=200)
    ordinal = models.IntegerField(default=1,editable=False)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["ordinal"]
        unique_together = ('parentProject', 'title',)
    def __str__(self):
        return self.title
    
class TabItem(models.Model):
    parentTabs = models.ForeignKey(Tabs)
    pageItem = models.ForeignKey(PageItem)
    top = models.IntegerField(default=50)
    left = models.IntegerField(default=50)
    width = models.IntegerField(default=200)
    height = models.IntegerField(default=200)
    zindex = models.IntegerField(default=1)
    html = models.CharField(max_length=1000,default='',blank=True)
    updated = models.DateTimeField(auto_now=True)
    def toCSS(self):
        #this is direct css
        return "background: url('/static/images/"+str(self.pageItem.stockImage)+"') no-repeat; background-size: 100%; top: "+str(self.top)+"; left: "+str(self.left)+"; width: "+str(self.width)+"; height: "+str(self.height)
    def __str__(self):
        return self.id
    
class ProjectViewers(models.Model):
    viewer = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        unique_together = ('viewer', 'project',)
    def __str__(self):
        return self.viewer.username
    
class ProjectEditors(models.Model):
    editor = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        unique_together = ('editor', 'project',)
    def __str__(self):
        return self.editor.username
    

SoftwareProjects/forms.py
from django.forms import ModelForm
from SoftwareStories.SoftwareProjects.models import Project, Tabs, TabItem, ProjectViewers, ProjectEditors

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ('user',) 

class ViewerForm(ModelForm):
    class Meta:
        model = ProjectViewers
        fields = ('viewer',) 

class EditorForm(ModelForm):
    class Meta:
        model = ProjectEditors
        fields = ('editor',) 

class TabForm(ModelForm):
    class Meta:
        model = Tabs
        exclude = ('parentProject','ordinal','divWidth','divHeight',) 

class TabSiteChartForm(ModelForm):
    class Meta:
        model = Tabs
        exclude = ('title','ordinal','divWidth','divHeight',) 

class TabRenameForm(ModelForm):
    class Meta:
        model = Tabs
        fields = ('title',) 
        
class TabItemForm(ModelForm):
    class Meta:
        model = TabItem
        fields = ('height','width','zindex','top','left','html','parentTabs','pageItem',)
        
    

SoftwareProjects/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from SoftwareStories.SoftwareProjects.models import Project, ProjectViewers, ProjectEditors, Tabs, TabItem
from SoftwareStories.SoftwareProjects.forms import ProjectForm, ViewerForm, EditorForm, TabForm, TabItemForm, TabSiteChartForm
from SoftwareStories.WebDrawing.models import PageItem, SoftwareStory


@login_required
def project_create(request):
    if(request.method == 'POST'):
        projectForm = ProjectForm(request.POST)
        if(projectForm.is_valid()):
            project = projectForm.save(commit=False)
            project.user = request.user
            project.save()
            projectForm = ProjectForm()
            return HttpResponseRedirect("/project/list/")
    else:
        projectForm = ProjectForm()            
    projectList = Project.objects.filter(user=request.user)
    return render_to_response("Project.sub",RequestContext(request,locals()))

@login_required
def projects_read(request):
    projectForm = ProjectForm()
    projectList = Project.objects.filter(user=request.user)
    return render_to_response("Projects.html",RequestContext(request,locals()))

@login_required
def project_read(request,id):
    curProject = get_object_or_404(Project,pk=id)
    projectForm = ProjectForm()
    viewerForm = ViewerForm()
    editorForm = EditorForm()
    projectList = Project.objects.filter(user=request.user)
    projectViewList = ProjectViewers.objects.filter(project=curProject)
    projectEditList = ProjectEditors.objects.filter(project=curProject)
    return render_to_response("Project.html",RequestContext(request,locals()))

@login_required
def project_update(request):
    return render_to_response("Project.html",RequestContext(request,locals()))

@login_required
def project_delete(request,id):
    return render_to_response("Project.html",RequestContext(request,locals()))

#login_required
def viewer_delete(request,id):
    
    return render_to_response("ProjectViewer.sub",RequestContext(request,locals()))

@login_required
def viewer_create(request,id):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        viewerForm = ViewerForm(request.POST)
        if(viewerForm.is_valid()):
            viewer = viewerForm.save(commit=False)
            viewer.project = curProject
            viewer.save()
            viewerForm = ViewerForm()
    projectViewList = ProjectViewers.objects.filter(project=curProject)
    return render_to_response("ProjectViewer.sub",RequestContext(request,locals()))

@login_required
def editor_create(request,id):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        editorForm = EditorForm(request.POST)
        if(editorForm.is_valid()):
            editor = editorForm.save(commit=False)
            editor.project = curProject
            editor.save()
            editorForm = EditorForm()
    projectEditList = ProjectEditors.objects.filter(project=curProject)
    return render_to_response("ProjectEditor.sub",RequestContext(request,locals()))

@login_required
def project_canvas(request,id):
    curProject = get_object_or_404(Project,pk=id)
    addablePageItems = PageItem.objects.all()
    tabs = Tabs.objects.filter(parentProject=curProject).select_related()
    tabForm = TabForm()
    tabItemForm = TabItemForm()
    return render_to_response("Canvas.html",RequestContext(request,locals()))

@login_required
def tab_create(request,id):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        tabForm = TabForm(request.POST)
        if(tabForm.is_valid()):
            tab = tabForm.save(commit=False)
            tab.parentProject = curProject
            tab.save()
            tabForm = TabForm()
    return render_to_response("Tab.form",RequestContext(request,locals()))
    
@login_required
def tabitem_update(request, id, tabItemId):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        tabItemForm = TabItemForm(request.POST, instance = get_object_or_404(TabItem,pk=tabItemId))
        if(tabItemForm.is_valid()):
            tabItemForm.save()
            return render_to_response("ok.json",RequestContext(request,{'pk_id': tabItemId}))
    return render_to_response("fail.json",RequestContext(request,{'pk_id': '-1'}))

@login_required
def tabitem_create(request, id):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        tabItemForm = TabItemForm(request.POST)
        if(tabItemForm.is_valid()):
            tabItem = tabItemForm.save()
            return render_to_response("ok.json",RequestContext(request,{'pk_id': tabItem.id}))
    return render_to_response("fail.json",RequestContext(request,{'pk_id': '-1'}))

@login_required
def sitemap_read(request, id):
    curProject = get_object_or_404(Project,pk=id)
    tabs = Tabs.objects.filter(parentProject=curProject).select_related()
    tabSiteChartForm = TabSiteChartForm()
    return render_to_response("SiteMap.html",RequestContext(request,locals()))

@login_required
def tab_update(request, id, tabId):
    curProject = get_object_or_404(Project,pk=id)
    if(request.method == 'POST'):
        tabSiteChartForm = TabSiteChartForm(request.POST,instance=get_object_or_404(Tabs,pk=tabId))
        if tabSiteChartForm.is_valid():
            t = tabSiteChartForm.save()
            return render_to_response("ok.json",RequestContext(request,{'pk_id': tabId}))
    return render_to_response("fail.json",RequestContext(request,{'pk_id': -1}))

@login_required
def stories_read(request, id):
    #fix me, way to many queries
    curProject = Project.objects.select_related().get(pk=id)
    storyList = {}
    hoursTotal = 0
    for tab in Tabs.objects.filter(parentProject=curProject):
        for tabItem in TabItem.objects.filter(parentTabs=tab):
            for oneStory in PageItem.objects.filter(id=tabItem.pageItem.id).stories:
                storyList[oneStory.id] = oneStory.estimatesHours 
                hoursTotal = oneStory.estimatesHours
    return render_to_response("ManHours.html",RequestContext(request,locals()))
    

SoftwareProjects/templates/classic/Canvas.html
{% extends "Project.base" %}

{% block title %}Solenoid Home{% endblock %}

{% block head %}
{{ block.super }}
<style>
{% autoescape off %}{% for addableItem in addablePageItems %}
.{{ addableItem.cssName }}{ position: absolute; border: solid red 1px; {{ addableItem.toCSS }} }{% endfor %}{% endautoescape %}
.basicTab{height: 90%;}
</style>
<script>
function savePageItem(tabitem){
	var curTab = $(".ui-tabs-panel:not(.ui-tabs-hide)");
	$("#id_height").val($(this).height());
	$("#id_width").val($(this).width())
	//$("#id_zindex").val($(this).css("z-index"));
	$("#id_top").val($(this).position().top);
	$("#id_left").val($(this).position().left);
	$("#id_pageItem").val($(this).attr("pageItemType"));
	$("#id_parentTabs").val(curTab.attr("tabId"));
	var postData = $("#FormUpdateTabItem").serializeArray();
	$.ajax({
		url: '{% url tabitem_update curProject.id 1 %}'.replace(/1\/update\//i, $(this).attr("tabItemId")+"/update/"),
		type: 'POST', 
		data: postData, 
		success: function(){
			//alert(42);
		}
	});
}
function addPageItem(itemToAdd){
	var curTab = $(".ui-tabs-panel:not(.ui-tabs-hide)");
	var indexValue=curTab.attr("id");
	if(indexValue!="tabs-0"){
		var curPageItemId = $(itemToAdd).attr("pageItemId");
		var curTabId = curTab.attr("tabId");
		$("#id_pageItem").val(curPageItemId);
		$("#id_parentTabs").val(curTabId);
		postData = $("#FormUpdateTabItem").serializeArray();
		$.ajax({
			url: '{% url tabitem_create curProject.id %}', 
			type: 'POST',
			dataType: 'json',
			data: $("#FormUpdateTabItem").serializeArray(),
			success: function(data){
			//think of refactoring this and below div into a template
				$('<div tabItemId="'+data.pk+'" pageItemType="'+curPageItemId+'" parentTabId="'+curTab.attr("tabId")+'" class="'+$(itemToAdd).attr('cssName')+'" />').appendTo("#"+indexValue).resizable({stop: savePageItem, handles: 'n, e, s, w, ne, se, sw, nw'}).draggable({containment: "#"+indexValue, stop:savePageItem});
			}
		});
	}
}
$(document).ready(function (){
	$("#accordion").accordion({fillSpace: true});
	$(".addPageItem").click(function(){addPageItem(this);});
	$(function(){$("#tabs").tabs();});
	$("#InputSubmitTab").click(function(){event.preventDefault(); $("#tabs-0").load('{% url tab_create curProject.id %}',$("#FormCreateTab").serializeArray()); });
	{% for tab in tabs %}
		$("div[parentTabId={{ tab.id }}]").resizable({stop: savePageItem, handles: 'n, e, s, w, ne, se, sw, nw'}).draggable({containment: "#tabs-{{ tab.id }}", stop:savePageItem});;
	{% endfor %}
});
</script>
{% endblock %}

{% block finalBody %}
<div id="DivWorld" class="container-fluid">
	<div class="sidebar">
		<h2><a href="{% url projects_read %}">Projects Home</a></h2>
		<h2><a href="{% url sitemap_read curProject.id %}">Site Map</a></h2>
		<h2><a href="{% url stories_read curProject.id %}">Man Hours</a></h2>
		<div id="accordion">
	    	{% for addableItem in addablePageItems %}
    			{% ifchanged addableItem %}
    				<h3><a href="#">{{ addableItem }}</a></h3>{% endifchanged %}
    				<div><a href="#" class='addPageItem' cssName='{{ addableItem.cssName }}' pageItemId='{{ addableItem.id }}'>{{ addableItem.title }}</a></div>{% endfor %}
		</div>
	</div>
	<div class="content">
		<div id="DivCanvas">
			<div id="tabs">
				<ul>
				{% for tab in tabs %}
					<li><a href="#tabs-{{ tab.id }}">{{ tab }}</a></li>
				{% endfor %}
				<li><a href="#tabs-0">+ Create Tab</a></li>
				</ul>
				{% for tab in tabs %}
					<div id="tabs-{{ tab.id }}" tabId="{{ tab.id }}" class="basicTab">
						{% for tabitem in tab.tabitem_set.all %}
							<!-- refactor below statements into 1 item -->
							<div class='initTabItem' tabItemId="{{ tabitem.id  }}" pageItemType="{{ tabitem.pageItem.id }}" parentTabId="{{ tab.id }}" style="position: absolute; border: solid red 1px; {% autoescape off %}{{ tabitem.toCSS }};{% endautoescape %}"></div>
						{% endfor %}
					</div>
				{% endfor %}
				<div id="tabs-0" class="basicTab">
					{% include "Tab.form" %} 
				</div>			
			</div>
		</div>
	</div>
</div>
<div style="display:none; position: absolute;">
<form id="FormUpdateTabItem">
{% csrf_token %}
<ul>
{{ tabItemForm.as_ul }}
</ul>
</form>
</div>
{% endblock %}

SoftwareProjects/templates/classic/ManHours.html
{% extends "Project.base" %}

{% block title %}Solenoid Home{% endblock %}

{% block head %}
<link type="text/css" href="{{ STATIC_URL }}jquery-ui-1.8.16.custom/css/blitzer/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="{{ STATIC_URL }}jquery-ui-1.8.16.custom/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
$(document).ready(function (){
});
	google.load('visualization', '1', {packages:['orgchart']});
	google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Name');
        data.addColumn('string', 'Manager');
        data.addColumn('string', 'ToolTip');
        data.addRows([
        	[{v:'_0_', f:'<div tabId="">Site Root</div>'}, '', 'Root'],
			{% for tab in tabs %}
			//combine these lines
			{% if tab.parentTab %}
          	[{v:'_{{ tab.id }}_', f:'<div tabId="{{ tab.id }}" parentTabId="{{ tab.parentTab.id }}">{{ tab }}</div>'}, '_{{ tab.parentTab.id }}_', 'root child'],
          	{% else %}
          	[{v:'_{{ tab.id }}_', f:'<div tabId="{{ tab.id }}" parentTabId="">{{ tab }}</div>'}, '_0_', 'something stupid'],          	
          	{% endif %}
			{% endfor %}
        ]);
        var chart = new google.visualization.OrgChart(document.getElementById('chart_div'));
        chart.draw(data, {allowHtml:true});
		$(".google-visualization-orgchart-node").draggable({revert: 'invalid'});
		$( ".google-visualization-orgchart-node" ).droppable({
			accept: ".google-visualization-orgchart-node",
			drop: function( event, ui ) {
		    	$("#id_parentTab").val($(event.target).find("div").attr("tabId"));
		    	$.ajax({
    				url: '{% url tab_update curProject.id 1 %}'.replace(/update\/(\d+)\//i,"update/"+$(ui.draggable).find("div").attr("tabId")+"/"),
    				data: $("#FormUpdateTab").serializeArray(),
    				type: 'POST',
    				success: function(){
    					location.reload();
		    		} 
    			});
			}
		});
	}

</script>
{% endblock %}

{% block finalBody %}
<ul>
<li><a href='{% url project_canvas curProject.id %}'>Edit Wireframes</a></li>
<li><a href='{% url sitemap_read curProject.id %}'>Site Map</a></li>
<li><a href=''>Read-Only Wireframes</a></li>
</ul>
{{ storycount }}
</div>
{% endblock %}

SoftwareProjects/templates/classic/Project.html
{% extends "Project.base" %}

{% block title %}Solenoid Home{% endblock %}

{% block head %}
{{ block.super }}
<script>
$(document).ready(function (){
    $("#InputSubmitProject").live("click",function(){ 
    	event.preventDefault(); 
    	$("#DivProjects").load('{% url project_create %}',$("#FormCreateProject").serializeArray()); 
    });	
    $("#InputSubmitEditor").live("click",function(){ 
    	event.preventDefault(); 
    	$("#DivEditors").load('{% url editor_create curProject.id %}',$("#FormCreateEditor").serializeArray()); 
    });	
    $("#InputSubmitViewer").live("click",function(){ 
    	event.preventDefault(); 
    	$("#DivViewers").load('{% url viewer_create curProject.id %}',$("#FormCreateViewer").serializeArray()); 
    });	
    $(".deleteUser").click(function(){
    	//alert("try to delete "+$(this).attr("userid"));
    	$("#DivViewers").load('{% url viewer_delete curProject.id 1 %}'.replace(/1\/delete\//i, $(this).attr("userid")+'/delete/'));
    	alert("try to delete "+$(this).attr("userid"));
    });
});
</script>
{% endblock %}

{% block finalBody %}
<ul>
<li><a href='{% url project_canvas curProject.id %}'>Edit Wireframes</a></li>
<li><a href='{% url sitemap_read curProject.id %}'>Site Map</a></li>
<li><a href=''>Read-Only Wireframes</a></li>
</ul>
<div id="DivProjects">
{% include "Project.sub" %}
</div>
<div id="DivEditors">
{% include "ProjectEditor.sub" %}
</div>
<div id="DivViewers">
{% include "ProjectViewer.sub" %}
</div>
{% endblock %}

SoftwareProjects/templates/classic/Projects.html
{% extends "Project.base" %}

{% block title %}Solenoid Home{% endblock %}

{% block head %}
{{ block.super }}
<script>
$(document).ready(function (){
    $("#InputSubmitProject").click(function(){ 
    	event.preventDefault(); 
    	$("#DivProjects").load('{% url project_create %}',$("#FormCreateProject").serializeArray()); 
    });	
});
</script>
{% endblock %}

{% block finalBody %}
<div id="DivProjects">
{% include "Project.sub" %}
</div>
{% endblock %}

SoftwareProjects/templates/classic/SiteMap.html
{% extends "Project.base" %}

{% block title %}Solenoid Home{% endblock %}

{% block head %}
<link type="text/css" href="{{ STATIC_URL }}jquery-ui-1.8.16.custom/css/blitzer/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="{{ STATIC_URL }}jquery-ui-1.8.16.custom/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
$(document).ready(function (){
});
	google.load('visualization', '1', {packages:['orgchart']});
	google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Name');
        data.addColumn('string', 'Manager');
        data.addColumn('string', 'ToolTip');
        data.addRows([
        	[{v:'_0_', f:'<div tabId="">Site Root</div>'}, '', 'Root'],
			{% for tab in tabs %}
			//combine these lines
			{% if tab.parentTab %}
          	[{v:'_{{ tab.id }}_', f:'<div tabId="{{ tab.id }}" parentTabId="{{ tab.parentTab.id }}">{{ tab }}</div>'}, '_{{ tab.parentTab.id }}_', 'root child'],
          	{% else %}
          	[{v:'_{{ tab.id }}_', f:'<div tabId="{{ tab.id }}" parentTabId="">{{ tab }}</div>'}, '_0_', 'something stupid'],          	
          	{% endif %}
			{% endfor %}
        ]);
        var chart = new google.visualization.OrgChart(document.getElementById('chart_div'));
        chart.draw(data, {allowHtml:true});
		$(".google-visualization-orgchart-node").draggable({revert: 'invalid'});
		$( ".google-visualization-orgchart-node" ).droppable({
			accept: ".google-visualization-orgchart-node",
			drop: function( event, ui ) {
		    	$("#id_parentTab").val($(event.target).find("div").attr("tabId"));
		    	$.ajax({
    				url: '{% url tab_update curProject.id 1 %}'.replace(/update\/(\d+)\//i,"update/"+$(ui.draggable).find("div").attr("tabId")+"/"),
    				data: $("#FormUpdateTab").serializeArray(),
    				type: 'POST',
    				success: function(){
    					location.reload();
		    		} 
    			});
			}
		});
	}

</script>
{% endblock %}

{% block finalBody %}
<ul>
<li><a href='{% url project_canvas curProject.id %}'>Edit Wireframes</a></li>
<li><a href='{% url sitemap_read curProject.id %}'>Site Map</a></li>
<li><a href=''>Read-Only Wireframes</a></li>
</ul>
<div id='chart_div'></div>
<div style="visibility: hidden;">
{% include "TabSiteMap.form" %}
</div>
{% endblock %}